#docker-compose --file ./dc.prometheus.yml up -d > /job/log/dc.prometheus.log
prometheus-pg:
  container_name: support-prometheus-pg
  image: prom/pushgateway
  restart: always
  ports:
    - "9091:9091"

prometheus:
  container_name: support-prometheus
  image: prom/prometheus
  restart: always
  links:
    - prometheus-pg
  ports:
    - "9090:9090"
  volumes:
    - /job/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
