#docker-compose --file ./dc.prometheus.yml up -d > /job/log/dc.prometheus.log
prometheus:
  container_name: support-prometheus
  image: prom/prometheus
  ports:
   - "9090:9090"
  volumes:
   - /job/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

prometheus-pg:
  container_name: support-prometheus-pg
  image: prom/pushgateway
  ports:
   - "9091:9091"